2019-12-09 19:29:02,562 manager INFO 1.1.0
2019-12-09 19:29:02,562 manager INFO Copyright (C) 2003-2010
2019-12-09 19:29:02,562 manager INFO   Noriaki Ando
2019-12-09 19:29:02,562 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 19:29:02,562 manager INFO Manager starting.
2019-12-09 19:29:02,562 manager INFO Starting local logging.
2019-12-09 19:29:02,568 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 19:29:04,599 ManagerServant INFO Master manager not found
2019-12-09 19:29:04,601 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 19:29:04,601 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 19:29:04,611 ec_base INFO setRate(1000000.000000) done
2019-12-09 19:29:04,612 ec_base INFO setRate(1000.000000) done
2019-12-09 19:29:04,612 rtobject INFO 1 execution context was created.
2019-12-09 19:29:04,621 rtobject INFO Initial active configuration set is default.
2019-12-09 19:29:07,401 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 19:29:07,401 SdoServiceAdmin ERROR type  already exists.
2019-12-09 19:29:07,401 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 19:29:07,401 SdoServiceAdmin ERROR type d0f097a4-1c0e-4346-9d3e-ae36559c5255 already exists.
