2019-12-09 15:14:01,147 manager INFO 1.1.0
2019-12-09 15:14:01,147 manager INFO Copyright (C) 2003-2010
2019-12-09 15:14:01,147 manager INFO   Noriaki Ando
2019-12-09 15:14:01,147 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-09 15:14:01,147 manager INFO Manager starting.
2019-12-09 15:14:01,147 manager INFO Starting local logging.
2019-12-09 15:14:01,147 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-09 15:14:03,165 ManagerServant INFO Master manager not found
2019-12-09 15:14:03,167 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-09 15:14:03,168 LocalServiceAdmin INFO All the local services are enabled.
2019-12-09 15:14:03,184 manager INFO Component type conf file: Change.conf loaded.
2019-12-09 15:14:03,188 ec_base INFO setRate(1000000.000000) done
2019-12-09 15:14:03,188 ec_base INFO setRate(1000.000000) done
2019-12-09 15:14:03,190 rtobject INFO 1 execution context was created.
2019-12-09 15:14:03,194 rtobject INFO Initial active configuration set is default-set.
2019-12-09 15:14:11,769 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-09 15:14:11,769 SdoServiceAdmin ERROR type  already exists.
2019-12-09 15:14:11,769 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-09 15:14:11,769 SdoServiceAdmin ERROR type 2c7d9f6f-6f97-406d-85fa-eedf253f4808 already exists.
2019-12-09 15:27:24,844 rawdata WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 2262, in checkPorts
    if port._non_existent():
  File "C:\Python27\lib\site-packages\omniORB\CORBA.py", line 556, in _non_existent
    return self._obj.nonExistent()
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

2019-12-09 15:27:24,890 rawdata WARNING Dead connection: 2338dd1e-1a4b-11ea-88bc-40f02f22cc81
2019-12-09 15:27:27,032 rawdata WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\PortBase.py", line 836, in disconnect
    return p.notify_disconnect(connector_id)
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTM_IDL\RTC_idl.py", line 1207, in notify_disconnect
    return self._obj.invoke("notify_disconnect", _0_RTC.PortService._d_notify_disconnect, args)
TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)

