2019-12-07 20:03:18,367 manager INFO 1.1.0
2019-12-07 20:03:18,367 manager INFO Copyright (C) 2003-2010
2019-12-07 20:03:18,367 manager INFO   Noriaki Ando
2019-12-07 20:03:18,367 manager INFO   Intelligent Systems Research Institute, AIST
2019-12-07 20:03:18,367 manager INFO Manager starting.
2019-12-07 20:03:18,367 manager INFO Starting local logging.
2019-12-07 20:03:18,382 manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-12-07 20:03:20,430 ManagerServant INFO Master manager not found
2019-12-07 20:03:20,430 manager WARNING Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\Manager.py", line 1900, in initManagerServant
    reffile = file(self._config.getProperty("manager.refstring_path"),'w')
IOError: [Errno 2] No such file or directory: '/var/log/rtcmanager.ref'

2019-12-07 20:03:20,430 LocalServiceAdmin INFO All the local services are enabled.
2019-12-07 20:03:20,444 manager INFO Component type conf file: Change.conf loaded.
2019-12-07 20:03:20,444 ec_base INFO setRate(1000000.000000) done
2019-12-07 20:03:20,444 ec_base INFO setRate(1000.000000) done
2019-12-07 20:03:20,444 rtobject INFO 1 execution context was created.
2019-12-07 20:03:20,444 rtobject INFO Initial active configuration set is default-set.
2019-12-07 20:03:24,335 SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-12-07 20:03:24,335 SdoServiceAdmin ERROR type  already exists.
2019-12-07 20:03:24,335 SdoServiceAdmin WARNING No available SDO service in the factory: IDL:OpenRTM/ComponentObserver:1.0
2019-12-07 20:03:24,335 SdoServiceAdmin ERROR type 9063759e-a10e-4652-b388-96e94c769afc already exists.
2019-12-07 20:03:32,394 rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1560, in on_execute
    ret = self.onExecute(ec_id)
  File "C:\workspacess\Change\Change.py", line 148, in onExecute
    FSR_lise[i] = float (rawdata[i-1])
IndexError: list assignment index out of range

2019-12-07 20:03:38,778 ec_worker ERROR State of the RTC is not ACTIVE_STATE.
